# Generated by Django 5.2.12 on 2026-05-08 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guru", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutiveFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="analysisartifact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("clause_table", "Clause table"),
                    ("paragraph_map", "Paragraph map"),
                    ("executive_read", "Executive read"),
                    ("suggestions", "Suggestions"),
                    ("trace", "Trace"),
                ],
                max_length=32,
            ),
        ),
    ]
